// Code generated by protoc-gen-go. DO NOT EDIT.
// source: User_FindByRollAndName.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User_FindByRollAndNameRequest struct {
	Query *User_Query `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// default value will be considered as __ALL__. Otherwise, we would consider the values provided
	Fields               []User_Fields `protobuf:"varint,2,rep,packed,name=fields,proto3,enum=storage.User_Fields" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *User_FindByRollAndNameRequest) Reset()         { *m = User_FindByRollAndNameRequest{} }
func (m *User_FindByRollAndNameRequest) String() string { return proto.CompactTextString(m) }
func (*User_FindByRollAndNameRequest) ProtoMessage()    {}
func (*User_FindByRollAndNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_19558d2f38bb5b79, []int{0}
}

func (m *User_FindByRollAndNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_FindByRollAndNameRequest.Unmarshal(m, b)
}
func (m *User_FindByRollAndNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_FindByRollAndNameRequest.Marshal(b, m, deterministic)
}
func (m *User_FindByRollAndNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_FindByRollAndNameRequest.Merge(m, src)
}
func (m *User_FindByRollAndNameRequest) XXX_Size() int {
	return xxx_messageInfo_User_FindByRollAndNameRequest.Size(m)
}
func (m *User_FindByRollAndNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_User_FindByRollAndNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_User_FindByRollAndNameRequest proto.InternalMessageInfo

func (m *User_FindByRollAndNameRequest) GetQuery() *User_Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *User_FindByRollAndNameRequest) GetFields() []User_Fields {
	if m != nil {
		return m.Fields
	}
	return nil
}

type User_FindByRollAndNameResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User_FindByRollAndNameResponse) Reset()         { *m = User_FindByRollAndNameResponse{} }
func (m *User_FindByRollAndNameResponse) String() string { return proto.CompactTextString(m) }
func (*User_FindByRollAndNameResponse) ProtoMessage()    {}
func (*User_FindByRollAndNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_19558d2f38bb5b79, []int{1}
}

func (m *User_FindByRollAndNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_FindByRollAndNameResponse.Unmarshal(m, b)
}
func (m *User_FindByRollAndNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_FindByRollAndNameResponse.Marshal(b, m, deterministic)
}
func (m *User_FindByRollAndNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_FindByRollAndNameResponse.Merge(m, src)
}
func (m *User_FindByRollAndNameResponse) XXX_Size() int {
	return xxx_messageInfo_User_FindByRollAndNameResponse.Size(m)
}
func (m *User_FindByRollAndNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_User_FindByRollAndNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_User_FindByRollAndNameResponse proto.InternalMessageInfo

func (m *User_FindByRollAndNameResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type User_Query struct {
	Roll      int64                `protobuf:"varint,1,opt,name=Roll,proto3" json:"Roll,omitempty"`
	DeletedAt *timestamp.Timestamp `protobuf:"bytes,2,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`
	UpdatedAt *timestamp.Timestamp `protobuf:"bytes,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	// config has contains and thus, repeated array is created
	Name                 []string `protobuf:"bytes,4,rep,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User_Query) Reset()         { *m = User_Query{} }
func (m *User_Query) String() string { return proto.CompactTextString(m) }
func (*User_Query) ProtoMessage()    {}
func (*User_Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_19558d2f38bb5b79, []int{2}
}

func (m *User_Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_Query.Unmarshal(m, b)
}
func (m *User_Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_Query.Marshal(b, m, deterministic)
}
func (m *User_Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_Query.Merge(m, src)
}
func (m *User_Query) XXX_Size() int {
	return xxx_messageInfo_User_Query.Size(m)
}
func (m *User_Query) XXX_DiscardUnknown() {
	xxx_messageInfo_User_Query.DiscardUnknown(m)
}

var xxx_messageInfo_User_Query proto.InternalMessageInfo

func (m *User_Query) GetRoll() int64 {
	if m != nil {
		return m.Roll
	}
	return 0
}

func (m *User_Query) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *User_Query) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User_Query) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

func init() {
	proto.RegisterType((*User_FindByRollAndNameRequest)(nil), "storage.User_FindByRollAndNameRequest")
	proto.RegisterType((*User_FindByRollAndNameResponse)(nil), "storage.User_FindByRollAndNameResponse")
	proto.RegisterType((*User_Query)(nil), "storage.User_Query")
}

func init() {
	proto.RegisterFile("User_FindByRollAndName.proto", fileDescriptor_19558d2f38bb5b79)
}

var fileDescriptor_19558d2f38bb5b79 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xc9, 0x9f, 0x56, 0x3a, 0x45, 0xc1, 0xd5, 0x43, 0x08, 0xfe, 0x09, 0xf1, 0x12, 0x41,
	0xb6, 0x10, 0x2f, 0x5e, 0x5b, 0xb4, 0x47, 0xc1, 0xc5, 0x5e, 0xbc, 0x48, 0x62, 0xa6, 0x31, 0x90,
	0x64, 0xd3, 0xcc, 0x06, 0xec, 0x37, 0xf2, 0x63, 0x4a, 0x76, 0x5b, 0x4b, 0x41, 0xe9, 0x6d, 0x98,
	0xf9, 0xbd, 0x37, 0x33, 0x0f, 0x2e, 0x16, 0x84, 0xed, 0xfb, 0xbc, 0xa8, 0xb3, 0xd9, 0x5a, 0xc8,
	0xb2, 0x9c, 0xd6, 0xd9, 0x73, 0x52, 0x21, 0x6f, 0x5a, 0xa9, 0x24, 0x3b, 0x22, 0x25, 0xdb, 0x24,
	0x47, 0xff, 0x3a, 0x97, 0x32, 0x2f, 0x71, 0xa2, 0xdb, 0x69, 0xb7, 0x9c, 0xa8, 0xa2, 0x42, 0x52,
	0x49, 0xd5, 0x18, 0xd2, 0x3f, 0xd5, 0x3e, 0xf4, 0xf1, 0x89, 0x55, 0x62, 0x5a, 0xe1, 0x17, 0x5c,
	0xfe, 0x6d, 0x2e, 0x70, 0xd5, 0x21, 0x29, 0x76, 0x0b, 0x83, 0x55, 0x87, 0xed, 0xda, 0xb3, 0x02,
	0x2b, 0x1a, 0xc7, 0x67, 0x7c, 0xb3, 0x8d, 0x6b, 0xd9, 0x4b, 0x3f, 0x12, 0x86, 0x60, 0x77, 0x30,
	0x5c, 0x16, 0x58, 0x66, 0xe4, 0xd9, 0x81, 0x13, 0x9d, 0xc4, 0xe7, 0xfb, 0xec, 0x5c, 0xcf, 0xc4,
	0x86, 0x09, 0x9f, 0xe0, 0xea, 0xbf, 0xcd, 0xd4, 0xc8, 0x9a, 0x90, 0xdd, 0xc0, 0xa0, 0x23, 0x6c,
	0xc9, 0xb3, 0x02, 0x27, 0x1a, 0xc7, 0xc7, 0x7b, 0x76, 0xc2, 0xcc, 0xc2, 0x6f, 0x0b, 0x60, 0x77,
	0x0a, 0x63, 0xe0, 0xf6, 0x56, 0xfa, 0x5a, 0x47, 0xe8, 0x9a, 0x3d, 0xc0, 0xe8, 0x11, 0x4b, 0x54,
	0x98, 0x4d, 0x95, 0x67, 0xeb, 0x37, 0x7c, 0x6e, 0xb2, 0xe2, 0xdb, 0xac, 0xf8, 0xeb, 0x36, 0x2b,
	0xb1, 0x83, 0x7b, 0xe5, 0xa2, 0xc9, 0x12, 0xa3, 0x74, 0x0e, 0x2b, 0x7f, 0xe1, 0xfe, 0x8e, 0xfe,
	0x17, 0xcf, 0x0d, 0x9c, 0x68, 0x24, 0x74, 0x3d, 0x73, 0xdf, 0xec, 0x26, 0x4d, 0x87, 0x5a, 0x78,
	0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x72, 0x92, 0x57, 0xd2, 0xd5, 0x01, 0x00, 0x00,
}
