// Code generated by protoc-gen-go. DO NOT EDIT.
// source: User_CreateUser.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User_CreateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User_CreateUserRequest) Reset()         { *m = User_CreateUserRequest{} }
func (m *User_CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*User_CreateUserRequest) ProtoMessage()    {}
func (*User_CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e86d0a5de9604ebe, []int{0}
}

func (m *User_CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_CreateUserRequest.Unmarshal(m, b)
}
func (m *User_CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *User_CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_CreateUserRequest.Merge(m, src)
}
func (m *User_CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_User_CreateUserRequest.Size(m)
}
func (m *User_CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_User_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_User_CreateUserRequest proto.InternalMessageInfo

func (m *User_CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type User_CreateUserResponse struct {
	UUID                 string   `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User_CreateUserResponse) Reset()         { *m = User_CreateUserResponse{} }
func (m *User_CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*User_CreateUserResponse) ProtoMessage()    {}
func (*User_CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e86d0a5de9604ebe, []int{1}
}

func (m *User_CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_CreateUserResponse.Unmarshal(m, b)
}
func (m *User_CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *User_CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_CreateUserResponse.Merge(m, src)
}
func (m *User_CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_User_CreateUserResponse.Size(m)
}
func (m *User_CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_User_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_User_CreateUserResponse proto.InternalMessageInfo

func (m *User_CreateUserResponse) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func init() {
	proto.RegisterType((*User_CreateUserRequest)(nil), "storage.User_CreateUserRequest")
	proto.RegisterType((*User_CreateUserResponse)(nil), "storage.User_CreateUserResponse")
}

func init() {
	proto.RegisterFile("User_CreateUser.proto", fileDescriptor_e86d0a5de9604ebe)
}

var fileDescriptor_e86d0a5de9604ebe = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0d, 0x2d, 0x4e, 0x2d,
	0x8a, 0x77, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x05, 0x31, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85,
	0xd8, 0x8b, 0x4b, 0xf2, 0x8b, 0x12, 0xd3, 0x53, 0xa5, 0x04, 0xc1, 0xf2, 0xc5, 0xc9, 0x19, 0xa9,
	0xb9, 0x89, 0x10, 0x39, 0x25, 0x6b, 0x2e, 0x31, 0x34, 0x4d, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5,
	0x25, 0x42, 0x8a, 0x5c, 0x2c, 0xa5, 0xc5, 0xa9, 0x45, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46,
	0xbc, 0x7a, 0x50, 0x43, 0xf4, 0xc0, 0x6a, 0xc0, 0x52, 0x4a, 0xba, 0x5c, 0xe2, 0x18, 0x9a, 0x8b,
	0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x84, 0xb8, 0x58, 0x42, 0x43, 0x3d, 0x5d, 0xc0, 0xba, 0x39,
	0x83, 0xc0, 0xec, 0x24, 0x36, 0xb0, 0x95, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x99, 0x36,
	0x30, 0x23, 0xa7, 0x00, 0x00, 0x00,
}
