// Code generated by protoc-gen-go. DO NOT EDIT.
// source: User_FindByRollAndName.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User_FindByRollAndNameRequest struct {
	Query                *User_FindByRollAndNameQuery `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *User_FindByRollAndNameRequest) Reset()         { *m = User_FindByRollAndNameRequest{} }
func (m *User_FindByRollAndNameRequest) String() string { return proto.CompactTextString(m) }
func (*User_FindByRollAndNameRequest) ProtoMessage()    {}
func (*User_FindByRollAndNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_19558d2f38bb5b79, []int{0}
}

func (m *User_FindByRollAndNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_FindByRollAndNameRequest.Unmarshal(m, b)
}
func (m *User_FindByRollAndNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_FindByRollAndNameRequest.Marshal(b, m, deterministic)
}
func (m *User_FindByRollAndNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_FindByRollAndNameRequest.Merge(m, src)
}
func (m *User_FindByRollAndNameRequest) XXX_Size() int {
	return xxx_messageInfo_User_FindByRollAndNameRequest.Size(m)
}
func (m *User_FindByRollAndNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_User_FindByRollAndNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_User_FindByRollAndNameRequest proto.InternalMessageInfo

func (m *User_FindByRollAndNameRequest) GetQuery() *User_FindByRollAndNameQuery {
	if m != nil {
		return m.Query
	}
	return nil
}

type User_FindByRollAndNameResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User_FindByRollAndNameResponse) Reset()         { *m = User_FindByRollAndNameResponse{} }
func (m *User_FindByRollAndNameResponse) String() string { return proto.CompactTextString(m) }
func (*User_FindByRollAndNameResponse) ProtoMessage()    {}
func (*User_FindByRollAndNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_19558d2f38bb5b79, []int{1}
}

func (m *User_FindByRollAndNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_FindByRollAndNameResponse.Unmarshal(m, b)
}
func (m *User_FindByRollAndNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_FindByRollAndNameResponse.Marshal(b, m, deterministic)
}
func (m *User_FindByRollAndNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_FindByRollAndNameResponse.Merge(m, src)
}
func (m *User_FindByRollAndNameResponse) XXX_Size() int {
	return xxx_messageInfo_User_FindByRollAndNameResponse.Size(m)
}
func (m *User_FindByRollAndNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_User_FindByRollAndNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_User_FindByRollAndNameResponse proto.InternalMessageInfo

func (m *User_FindByRollAndNameResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type User_FindByRollAndNameQuery struct {
	Roll int64 `protobuf:"varint,1,opt,name=Roll,proto3" json:"Roll,omitempty"`
	// config has contains and thus, repeated array is created
	Name                 []string `protobuf:"bytes,4,rep,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User_FindByRollAndNameQuery) Reset()         { *m = User_FindByRollAndNameQuery{} }
func (m *User_FindByRollAndNameQuery) String() string { return proto.CompactTextString(m) }
func (*User_FindByRollAndNameQuery) ProtoMessage()    {}
func (*User_FindByRollAndNameQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_19558d2f38bb5b79, []int{2}
}

func (m *User_FindByRollAndNameQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_FindByRollAndNameQuery.Unmarshal(m, b)
}
func (m *User_FindByRollAndNameQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_FindByRollAndNameQuery.Marshal(b, m, deterministic)
}
func (m *User_FindByRollAndNameQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_FindByRollAndNameQuery.Merge(m, src)
}
func (m *User_FindByRollAndNameQuery) XXX_Size() int {
	return xxx_messageInfo_User_FindByRollAndNameQuery.Size(m)
}
func (m *User_FindByRollAndNameQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_User_FindByRollAndNameQuery.DiscardUnknown(m)
}

var xxx_messageInfo_User_FindByRollAndNameQuery proto.InternalMessageInfo

func (m *User_FindByRollAndNameQuery) GetRoll() int64 {
	if m != nil {
		return m.Roll
	}
	return 0
}

func (m *User_FindByRollAndNameQuery) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

func init() {
	proto.RegisterType((*User_FindByRollAndNameRequest)(nil), "storage.User_FindByRollAndNameRequest")
	proto.RegisterType((*User_FindByRollAndNameResponse)(nil), "storage.User_FindByRollAndNameResponse")
	proto.RegisterType((*User_FindByRollAndNameQuery)(nil), "storage.User_FindByRollAndNameQuery")
}

func init() {
	proto.RegisterFile("User_FindByRollAndName.proto", fileDescriptor_19558d2f38bb5b79)
}

var fileDescriptor_19558d2f38bb5b79 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x09, 0x2d, 0x4e, 0x2d,
	0x8a, 0x77, 0xcb, 0xcc, 0x4b, 0x71, 0xaa, 0x0c, 0xca, 0xcf, 0xc9, 0x71, 0xcc, 0x4b, 0xf1, 0x4b,
	0xcc, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x2e, 0xc9, 0x2f, 0x4a, 0x4c,
	0x4f, 0x95, 0x12, 0x04, 0x2b, 0x2b, 0x4e, 0xce, 0x48, 0xcd, 0x4d, 0x84, 0xc8, 0x29, 0x45, 0x73,
	0xc9, 0x62, 0xd7, 0x1b, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x64, 0xc5, 0xc5, 0x5a, 0x58,
	0x9a, 0x5a, 0x54, 0x29, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x6d, 0xa4, 0xa2, 0x07, 0x35, 0x4c, 0x0f,
	0xbb, 0xb6, 0x40, 0x90, 0xda, 0x20, 0x88, 0x16, 0x25, 0x57, 0x2e, 0x39, 0x5c, 0x86, 0x17, 0x17,
	0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x29, 0x73, 0xb1, 0x96, 0x16, 0xa7, 0x16, 0x15, 0x4b, 0x30, 0x2a,
	0x30, 0x6b, 0x70, 0x1b, 0xf1, 0xa2, 0x98, 0x1e, 0x04, 0x91, 0x53, 0x72, 0xe5, 0x92, 0xc6, 0x63,
	0x99, 0x90, 0x10, 0x17, 0x0b, 0x48, 0x0c, 0xec, 0x40, 0xe6, 0x20, 0x30, 0x1b, 0x24, 0x06, 0x52,
	0x20, 0xc1, 0xa2, 0xc0, 0xac, 0xc1, 0x19, 0x04, 0x66, 0x3b, 0xb1, 0x44, 0x31, 0x15, 0x24, 0x25,
	0xb1, 0x81, 0xfd, 0x6d, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xd4, 0xe7, 0xdf, 0xee, 0x33, 0x01,
	0x00, 0x00,
}
