// Code generated by protoc-gen-go. DO NOT EDIT.
// source: User_schema.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	UUID                 string               `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Roll                 int64                `protobuf:"varint,3,opt,name=Roll,proto3" json:"Roll,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_31e10b46f8220c3d, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetRoll() int64 {
	if m != nil {
		return m.Roll
	}
	return 0
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "storage.User")
}

func init() {
	proto.RegisterFile("User_schema.proto", fileDescriptor_31e10b46f8220c3d)
}

var fileDescriptor_31e10b46f8220c3d = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8d, 0xb1, 0x4e, 0xc5, 0x20,
	0x18, 0x46, 0x43, 0x8b, 0x35, 0xc5, 0x49, 0x26, 0xd2, 0xc5, 0xc6, 0xa9, 0x13, 0x4d, 0x74, 0x71,
	0x55, 0xbb, 0xb8, 0x38, 0x10, 0x59, 0x5c, 0x0c, 0xb5, 0xbf, 0xd5, 0x04, 0x02, 0x01, 0x7c, 0x6f,
	0x1f, 0xc1, 0x00, 0xb7, 0xbd, 0x63, 0xb7, 0x2f, 0x27, 0xe7, 0xe4, 0x23, 0xd7, 0x32, 0x80, 0xff,
	0x08, 0x9f, 0xdf, 0x60, 0x14, 0x77, 0xde, 0x46, 0x4b, 0x2f, 0x43, 0xb4, 0x5e, 0xad, 0xd0, 0xdd,
	0xac, 0xd6, 0xae, 0x1a, 0xc6, 0x8c, 0xe7, 0xdf, 0xaf, 0x31, 0xfe, 0x18, 0x08, 0x51, 0x19, 0x57,
	0xcc, 0xdb, 0x3f, 0x44, 0x70, 0xea, 0x29, 0x25, 0x58, 0xca, 0x97, 0x89, 0xa1, 0x1e, 0x0d, 0xad,
	0xc8, 0x3b, 0xb1, 0x57, 0x65, 0x80, 0x55, 0x85, 0xa5, 0x9d, 0x98, 0xb0, 0x5a, 0xb3, 0xba, 0x47,
	0x43, 0x2d, 0xf2, 0xa6, 0x0f, 0xa4, 0x7d, 0xf6, 0xa0, 0x22, 0x2c, 0x8f, 0x91, 0xe1, 0x1e, 0x0d,
	0x57, 0x77, 0x1d, 0x2f, 0xcf, 0x7c, 0x7b, 0xe6, 0x6f, 0xdb, 0xb3, 0x38, 0xcb, 0xa9, 0x94, 0x6e,
	0x39, 0x95, 0x17, 0xc7, 0xe5, 0x2e, 0xa7, 0x72, 0x02, 0x0d, 0xa5, 0x6c, 0x8e, 0xcb, 0x5d, 0x7e,
	0xc2, 0xef, 0x95, 0x9b, 0xe7, 0x26, 0x4b, 0xf7, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x20,
	0x2e, 0xc1, 0x3e, 0x01, 0x00, 0x00,
}
