// Code generated by protoc-gen-go. DO NOT EDIT.
// source: User_schema.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// generated with every schema change
type User_Fields int32

const (
	User_Fields_Name      User_Fields = 0
	User_Fields_Roll      User_Fields = 1
	User_Fields_CreatedAt User_Fields = 2
	User_Fields_UpdatedAt User_Fields = 3
	User_Fields_DeletedAt User_Fields = 4
	User_Fields___ALL__   User_Fields = 5
)

var User_Fields_name = map[int32]string{
	0: "Name",
	1: "Roll",
	2: "CreatedAt",
	3: "UpdatedAt",
	4: "DeletedAt",
	5: "__ALL__",
}

var User_Fields_value = map[string]int32{
	"Name":      0,
	"Roll":      1,
	"CreatedAt": 2,
	"UpdatedAt": 3,
	"DeletedAt": 4,
	"__ALL__":   5,
}

func (x User_Fields) String() string {
	return proto.EnumName(User_Fields_name, int32(x))
}

func (User_Fields) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_31e10b46f8220c3d, []int{0}
}

type User struct {
	Name                 string               `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Roll                 int64                `protobuf:"varint,2,opt,name=Roll,proto3" json:"Roll,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_31e10b46f8220c3d, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetRoll() int64 {
	if m != nil {
		return m.Roll
	}
	return 0
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func init() {
	proto.RegisterEnum("storage.User_Fields", User_Fields_name, User_Fields_value)
	proto.RegisterType((*User)(nil), "storage.User")
}

func init() {
	proto.RegisterFile("User_schema.proto", fileDescriptor_31e10b46f8220c3d)
}

var fileDescriptor_31e10b46f8220c3d = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x71, 0xe2, 0x52, 0xea, 0x08, 0xc9, 0x78, 0x8a, 0xba, 0x10, 0x31, 0x45, 0x0c, 0xa9,
	0x04, 0x0b, 0x6b, 0x01, 0x31, 0x55, 0x0c, 0x11, 0x5d, 0x60, 0xb0, 0x1c, 0x72, 0x84, 0x4a, 0x8e,
	0x1c, 0xd9, 0xe6, 0xdf, 0xf2, 0x63, 0xd0, 0xd9, 0xd4, 0xb0, 0x65, 0x7b, 0x77, 0x7a, 0x9f, 0x9f,
	0xdf, 0xb1, 0x8b, 0xbd, 0x03, 0x2b, 0xdd, 0xfb, 0x27, 0x8c, 0xaa, 0x99, 0xac, 0xf1, 0x46, 0x2c,
	0x9d, 0x37, 0x56, 0x0d, 0xb0, 0xbe, 0x1c, 0x8c, 0x19, 0x34, 0x6c, 0xc2, 0xba, 0xfb, 0xfa, 0xd8,
	0xf8, 0xc3, 0x08, 0xce, 0xab, 0x71, 0x8a, 0xce, 0xab, 0x6f, 0xc2, 0x28, 0xf2, 0x42, 0x30, 0xfa,
	0xac, 0x46, 0x28, 0x49, 0x45, 0xea, 0x55, 0x1b, 0x34, 0xee, 0x5a, 0xa3, 0x75, 0x99, 0x55, 0xa4,
	0xce, 0xdb, 0xa0, 0xc5, 0x1d, 0x5b, 0x3d, 0x58, 0x50, 0x1e, 0xfa, 0xad, 0x2f, 0xf3, 0x8a, 0xd4,
	0xc5, 0xcd, 0xba, 0x89, 0x29, 0xcd, 0x31, 0xa5, 0x79, 0x39, 0xa6, 0xb4, 0x7f, 0x66, 0x24, 0xf7,
	0x53, 0xff, 0x4b, 0xd2, 0x79, 0x32, 0x99, 0x91, 0x7c, 0x04, 0x0d, 0x91, 0x5c, 0xcc, 0x93, 0xc9,
	0x7c, 0xfd, 0xc6, 0x8a, 0x70, 0x9d, 0xa7, 0x03, 0xe8, 0xde, 0x89, 0xb3, 0x58, 0x92, 0x9f, 0xa0,
	0xc2, 0x3a, 0x9c, 0x88, 0xf3, 0x7f, 0x85, 0x78, 0x86, 0x63, 0x0a, 0xe6, 0x39, 0x8e, 0xe9, 0x35,
	0x4e, 0x45, 0xc1, 0x96, 0x52, 0x6e, 0x77, 0x3b, 0x29, 0xf9, 0xe2, 0x9e, 0xbe, 0x66, 0x53, 0xd7,
	0x9d, 0x86, 0x1f, 0xdc, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x04, 0xcf, 0x06, 0x87, 0x01,
	0x00, 0x00,
}
