// Code generated by protoc-gen-go. DO NOT EDIT.
// source: User_UpdateUsers.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User_UpdateUsersRequest struct {
	Entities             []*User  `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User_UpdateUsersRequest) Reset()         { *m = User_UpdateUsersRequest{} }
func (m *User_UpdateUsersRequest) String() string { return proto.CompactTextString(m) }
func (*User_UpdateUsersRequest) ProtoMessage()    {}
func (*User_UpdateUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a59f022c8cafe3a4, []int{0}
}

func (m *User_UpdateUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_UpdateUsersRequest.Unmarshal(m, b)
}
func (m *User_UpdateUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_UpdateUsersRequest.Marshal(b, m, deterministic)
}
func (m *User_UpdateUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_UpdateUsersRequest.Merge(m, src)
}
func (m *User_UpdateUsersRequest) XXX_Size() int {
	return xxx_messageInfo_User_UpdateUsersRequest.Size(m)
}
func (m *User_UpdateUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_User_UpdateUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_User_UpdateUsersRequest proto.InternalMessageInfo

func (m *User_UpdateUsersRequest) GetEntities() []*User {
	if m != nil {
		return m.Entities
	}
	return nil
}

type User_UpdateUsersResponse struct {
	Entities             []*User  `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User_UpdateUsersResponse) Reset()         { *m = User_UpdateUsersResponse{} }
func (m *User_UpdateUsersResponse) String() string { return proto.CompactTextString(m) }
func (*User_UpdateUsersResponse) ProtoMessage()    {}
func (*User_UpdateUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a59f022c8cafe3a4, []int{1}
}

func (m *User_UpdateUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_UpdateUsersResponse.Unmarshal(m, b)
}
func (m *User_UpdateUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_UpdateUsersResponse.Marshal(b, m, deterministic)
}
func (m *User_UpdateUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_UpdateUsersResponse.Merge(m, src)
}
func (m *User_UpdateUsersResponse) XXX_Size() int {
	return xxx_messageInfo_User_UpdateUsersResponse.Size(m)
}
func (m *User_UpdateUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_User_UpdateUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_User_UpdateUsersResponse proto.InternalMessageInfo

func (m *User_UpdateUsersResponse) GetEntities() []*User {
	if m != nil {
		return m.Entities
	}
	return nil
}

func init() {
	proto.RegisterType((*User_UpdateUsersRequest)(nil), "storage.User_UpdateUsersRequest")
	proto.RegisterType((*User_UpdateUsersResponse)(nil), "storage.User_UpdateUsersResponse")
}

func init() {
	proto.RegisterFile("User_UpdateUsers.proto", fileDescriptor_a59f022c8cafe3a4)
}

var fileDescriptor_a59f022c8cafe3a4 = []byte{
	// 135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0b, 0x2d, 0x4e, 0x2d,
	0x8a, 0x0f, 0x2d, 0x48, 0x49, 0x2c, 0x49, 0x05, 0x31, 0x8b, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2,
	0x85, 0xd8, 0x8b, 0x4b, 0xf2, 0x8b, 0x12, 0xd3, 0x53, 0xa5, 0x04, 0xc1, 0x0a, 0x8a, 0x93, 0x33,
	0x52, 0x73, 0x13, 0x21, 0x72, 0x4a, 0x2e, 0x5c, 0xe2, 0xe8, 0xba, 0x82, 0x52, 0x0b, 0x4b, 0x53,
	0x8b, 0x4b, 0x84, 0x34, 0xb9, 0x38, 0x52, 0xf3, 0x4a, 0x32, 0x4b, 0x32, 0x53, 0x8b, 0x25, 0x18,
	0x15, 0x98, 0x35, 0xb8, 0x8d, 0x78, 0xf5, 0xa0, 0x26, 0xe9, 0x81, 0x14, 0x06, 0xc1, 0xa5, 0x95,
	0x5c, 0xb9, 0x24, 0x30, 0x4d, 0x29, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x25, 0xc1, 0x18, 0x27, 0x96,
	0x28, 0xa6, 0x82, 0xa4, 0x24, 0x36, 0xb0, 0xcb, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x25,
	0xe4, 0x85, 0x61, 0xcf, 0x00, 0x00, 0x00,
}
