table: jobs
schema:
#all fields present in storage with their types
fields:
  - fieldName: UUID
    fieldType: string
    primaryKey: true
  - fieldName: Position
    fieldType: string
  - fieldName: Company
    fieldType: string
  - fieldName: CreatedBy
    fieldType: string
  - fieldName: CreatedAt
    fieldType: timestamp
  - fieldName: UpdatedAt
    fieldType: timestamp
  - fieldName: DeletedAt
    fieldType: timestamp

views:
  - name: CreateJob
    type: CREATE
    config:
      returnType: primaryKey
      multiReturn: true

