table: JobApplications
schema:
#all fields present in storage with their types
fields:
  - fieldName: UserUUID
    fieldType: string
    primaryKey: true
  - fieldName: JobUUID
    fieldType: string
    primaryKey: true
  - fieldName: CreatedAt
    fieldType: timestamp
  - fieldName: UpdatedAt
    fieldType: timestamp
  - fieldName: DeletedAt
    fieldType: timestamp

views: