table: users
schema:
#all fields present in storage with their types
fields:
  - fieldName: UUID
    fieldType: string
    primaryKey: true
  - fieldName: Name
    fieldType: string
    notNull: true
  - fieldName: Roll
    fieldType: int64
  - fieldName: CreatedAt
    fieldType: Timestamp
  - fieldName: UpdatedAt
    fieldType: Timestamp
  - fieldName: DeletedAt
    fieldType: string

views:
  - name: FindByRollAndName
    type: READ
    query:
      fields:
        - fieldName: Roll
          searchType: EQUALS
          optional: false
        - fieldName: UpdatedAt
          searchType: GREATER_THAN
          optional: true
        - fieldName: Name
          searchType: CONTAINS
          optional: true

  - name: CreateUser
    type: CREATE
    multiple: false
    returnType: primaryKey

  - name: UpdateUsers
    type: UPDATE
    multiple: true
    returnType: data

  - name: DeleteUsers
    type: DELETE
    multiple: true
    returnType: dataCount
